webapp/webapp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView

from chat.views import *
from goods.views import *
from team.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', TokenLoginView.as_view(), name='login'),
    #url(r'^tokens-print-em-all/$', TokensView.as_view(), name='tokens-print'),
    url(r'^logout/$', LogoutView.as_view(template_name='logout.html'), name='logout'),
    url(r'^mine/$', MineView.as_view(), name='mine'),
    url(r'^storage/$', StorageView.as_view(), name='storage'),
    url(r'^market/$', MarketView.as_view(), name='market'),
    url(r'^sell/([0-9]+)/start-([0-9]+)$', SellView.as_view(), name='sell'),
    url(r'^sell/([0-9]+)/abort$', AbortQuestView.as_view(), name='abort-quest'),
    url(r'^sell/([0-9]+)/finish$', FinishQuestView.as_view(), name='finish-quest'),
    url(r'^scoreboard/$', ScoreView.as_view(), name='score'),
    url(r'^channel/([0-9]+)$', ChannelView.as_view(), name='channel'),

    url(r'^ajax/scoreboard/$', AjaxScoreView.as_view(), name='ajax-score'),
    url(r'^ajax/channel/([0-9]+)$', MessagesView.as_view(), name='ajax-channel'),

    url(r'^$', login_required(TemplateView.as_view(template_name='homepage.html')), name='homepage'),
]

webapp/chat/models.py
from datetime import timedelta, datetime

from django.db import models
from django.db.models import Q
from django.urls import resolve, reverse
from django.utils import timezone

from team.models import Player, PlayerMenuItem


class Channel(models.Model):
    players = models.ManyToManyField(Player)

    # The messages are queued through leaky bucket. The minimal delay is MAX_REFRESH_PERIOD,
    # and at most one message per MIN_MESSAGE_PERIOD is sent.
    MAX_REFRESH_PERIOD = timedelta(seconds=3)
    MIN_MESSAGE_PERIOD = timedelta(seconds=60)

    class Meta:
        permissions = (
            ('channel.admin', 'View all channels, send without delay'),
        )

    def __str__(self):
        return "Channel: {} msgs, {}".format(self.message_set.count(), ", ".join(str(p) for p in self.players.all()))

    def get_next_refresh_time(self) -> timedelta:
        try:
            first_msg = self.message_set.filter(visible__gt=timezone.now())[0]
            to_first_msg = first_msg.visible - timezone.now()
            return min(to_first_msg, Channel.MAX_REFRESH_PERIOD)
        except IndexError:
            return Channel.MAX_REFRESH_PERIOD

    def get_visible_messages(self, for_player):
        return self.message_set.filter(Q(visible__lte=timezone.now()) | Q(author=for_player))

    def get_next_visible_time(self, message) -> datetime:
        if message.author.user.has_perm('channel.admin'):
            return timezone.now()
        try:
            last_visible = self.message_set.filter(author=message.author).order_by('-visible')[0].visible
            after_last_msg = last_visible + Channel.MIN_MESSAGE_PERIOD

            typing_delay = last_visible + ((len(message.content) / 300) * timedelta(seconds=1))
            return max(after_last_msg, typing_delay, timezone.now() + Channel.MAX_REFRESH_PERIOD)
        except IndexError:
            return timezone.now() + Channel.MAX_REFRESH_PERIOD

    def post(self, author, content):
        msg = Message()
        msg.author = author
        msg.channel = self
        msg.posted = timezone.now()
        msg.content = content
        msg.visible = self.get_next_visible_time(msg)
        return msg.save()


class Message(models.Model):
    channel = models.ForeignKey(Channel, on_delete=models.PROTECT)
    author = models.ForeignKey(Player, on_delete=models.PROTECT)
    posted = models.DateTimeField()
    visible = models.DateTimeField()
    content = models.TextField()

    class Meta:
        ordering = ['posted']

    def is_visible(self):
        return self.visible <= timezone.now()

webapp/team/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum


class Team(models.Model):
    name = models.CharField(max_length=256, unique=True, verbose_name="Název týmu")
    members = models.TextField(verbose_name="Seznam členů")

    def __str__(self):
        return self.name

    def get_score(self):
        return self.goods_set.filter(sold_for__isnull=False).aggregate(Sum('sold_for'))

    @classmethod
    def get_score_table(cls):
        return cls.objects.all().annotate(score=Sum('goods__sold_for')).order_by('-score')


class Player(models.Model):
    TOKEN_LEN = 10

    # Oh yeah, we store the "password" for players in plaintext.
    login_token = models.CharField(max_length=TOKEN_LEN)

    user = models.OneToOneField(User)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)

    # Name for the purpose of chatting
    name = models.TextField()
    # Name in instrumental
    instr = models.TextField()

    def __str__(self):
        return "{} / {}".format(self.team, self.user.first_name)


class PlayerMenuItem(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    label = models.CharField(max_length=64)
    url = models.CharField(max_length=128)

webapp/team/forms.py
from django import forms
from django.forms import Form

from team.models import Player


class TokenAuthenticationForm(Form):
    token = forms.CharField(min_length=Player.TOKEN_LEN, max_length=Player.TOKEN_LEN, label="Přihlašovací token",
                            widget=forms.TextInput(attrs={'autofocus': True}))
    error_messages = {
        'invalid_login': "Token je nesprávný."
    }

    def __init__(self, request=None, *args, **kwargs):
        """
        The 'request' parameter is set for custom auth use by subclasses.
        The form data comes in via the standard 'data' kwarg.
        """
        self.request = request
        self.user_cache = None
        super(TokenAuthenticationForm, self).__init__(*args, **kwargs)

    def clean(self):
        token = self.cleaned_data.get('token')
        player = Player.objects.filter(login_token=token).first()
        if player is None:
            raise forms.ValidationError(
                self.error_messages['invalid_login'],
                code='invalid_login',
            )
        self.user_cache = player.user

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache

webapp/team/views.py
from django.contrib.auth.views import LoginView
from django.http import HttpResponseForbidden
from django.views.generic import TemplateView

from team.forms import TokenAuthenticationForm
from team.models import Team


class TokenLoginView(LoginView):
    form_class = TokenAuthenticationForm
    template_name = 'login.html'
    redirect_authenticated_user = True

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            return HttpResponseForbidden()
        return super(TokenLoginView, self).dispatch(request, *args, **kwargs)


class AjaxScoreView(TemplateView):
    template_name = 'bits/score.html'

    def get_context_data(self, **kwargs):
        context = super(AjaxScoreView, self).get_context_data(**kwargs)
        context['score'] = Team.get_score_table()
        return context


class ScoreView(AjaxScoreView):
    template_name = "score.html"

webapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name = "viewport" content = "width = device-width, initial-scale = 1.0">
    <link href = "{% static 'css/bootstrap.css' %}" rel = "stylesheet">
    <link href = "{% static 'css/main.css' %}" rel = "stylesheet">
    <link href = "{% static 'css/sprites.css' %}" rel = "stylesheet">
    <title>{% block title %}Amazon{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'homepage' %}">Amazon
      {% if view.request.team %}: {{ view.request.team.name }}{% endif %}
      </a>
    </div>
    <div class="container-fluid">
        <ul class="nav navbar-nav navbar">
            <li><a href="{% url 'score' %}">Výsledky týmů</a></li>
            {% if user.is_authenticated %}
                {% if perms.goods.can_mine  %}
                    <li><a href="{% url 'mine' %}">Továrna</a></li>
                    <li><a href="{% url 'storage' %}">Sklad</a></li>
                {% endif %}
                {% if perms.goods.can_sell  %}
                    <li><a href="{% url 'market' %}">Trh</a></li>
                {% endif %}
                {% for mi in user.player.playermenuitem_set.all %}
                    <li><a href="{{ mi.url }}">{{ mi.label }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>
        <ul class="nav navbar-right navbar-nav">
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Odhlásit</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Přihlásit se</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

webapp/templates/channel.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}

<div class="messenger" id="messenger">
    {% include 'bits/channel.html' %}
</div>

<form method="post" role="form" id="id_form">
    {% csrf_token %}
    <div class="input-group">
        <textarea name="content" id="id_content" rows="1" class="form-control" autofocus></textarea>
        <span class="input-group-btn">
            <button type="submit" class="btn btn-primary center-block form-control">Odeslat</button>
        </span>
    </div>
</form>
<div class="text-center"><em>Tip: Enter odešle zprávu, Shift+Enter odřádkuje.</em></div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $('#id_content').keydown(function (e) {
      if (!e.shiftKey && e.keyCode == 13) {
          e.preventDefault();
          $("#id_form").submit();
      }
    });
    var messenger = $('#messenger');
    function refresh_messages() {
        $.ajax({
            url: "{% url 'ajax-channel' view.args.0 %}",
            success: function (data, textStatus, xhr) {
                doScroll = (messenger.scrollTop() === messenger[0].scrollHeight);
                messenger.html(data);
                if (doScroll)
                    messenger.scrollTop(messenger[0].scrollHeight);
                var refresh = parseInt(xhr.getResponseHeader('X-Refresh-After'));
                setTimeout(refresh_messages, refresh * 1000 + 420);
            }
        });
    }
    $(function() {
        var firstRefresh = {{ refresh_after | safe }};
        messenger.scrollTop(messenger[0].scrollHeight);
        setTimeout(refresh_messages, firstRefresh * 1000 + 420);
    });
</script>

{% endblock %}

webapp/templates/homepage.html
{% extends "base.html" %}
{% block content %}

Pokračuj v menu.
{% endblock %}

webapp/templates/login.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}

<h3>Přihlášení</h3>

{% if next %}
    {% if user.is_authenticated %}
    <div class="alert alert-danger">K této akci nemáš potřebné právo. Nechtěl jsi se přihlásit za někoho jiného?</div>
    {% else %}
    <p>Od orgů jste dostali lísteček s přihlašovacím tokenem. Nyní je ten správný čas jej použít.</p>
    {% endif %}
{% endif %}

<form method="post" role="form" action="{% url 'login' %}">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    {{ form|bootstrap }}
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Přihlásit</button>
    </div>
</form>


{% endblock %}

webapp/templates/logout.html
{% extends "base.html" %}
{% load bootstrap %}

{% block content %}

<div class="alert alert-success">Byl jsi odhlášen.</div>

<p><a href="{% url 'login' %}">Přihlásit se znovu.</a></p>

{% endblock %}

webapp/templates/score.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}
<table class="table table-balance" id="scoreboard">
    <thead>
    <tr>
        <th>Aktuální pořadí</th>
        <th>Tým</th>
        <th>Zisk</th>
    </tr>
    </thead>
    {% include 'bits/score.html' %}
</table>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    var sbody = $("#scoreboard").find('tbody');

    setInterval(function () {
        $.ajax({
            url: "{% url 'ajax-score' %}",
            success: function (data, textStatus, xhr) {
                sbody.replaceWith(data);
            }
        });
    }, 5000);
</script>
{% endblock %}

webapp/templates/sell.html
{% extends "base.html" %}
{% load bootstrap %}
{% block content %}

<p>Každý z vás může prodávat nezávisle, pokud zvládne aktivitu sám.</p>

<div class="row">
    {% for slot in slots %}
    <div class="col-sm-12 col-md-6">
        {% if slot.is_free %}
        <ul class="nav">
            {% for type in types %}
                <li><a href="{% url 'sell' slot.pk type.pk %}">{{ type.name }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            {{ slot.selling.sell_quest | safe }}

            <a href="{% url 'finish-quest' slot.pk %}" class="btn btn-primary center-block">Provedl jsem úkol</a>
            <a href="{% url 'abort-quest' slot.pk %}" class="btn btn-danger center-block">Vzdávám úkol</a>
        {% endif %}
    </div>
    {% endfor %}
</div>

{% endblock %}

webapp/templates/team.html
{% extends "base.html" %}
{% block title %}Tým {{ team.name }}{% endblock %}
{% block content %}

<h2>Inventář <small>{{ team.name }}</small></h2>

{% include "core/team_inventory.html" %}

{% endblock %}